package oop_principles.class_objects;

public class Car {
// Default constructor

    public Car(){

    }
    // by default            // Change default for each car in main
public String make;                 // public String = "BMW";
public String model;                // public String = " X6"'
public String color;
public int year;                    // public int = 2014;
public double price;
boolean hasRoof;


// defining some behaviors of the class

    // What car does?

    public void drives(){
        System.out.println("This car drives");
    }

    public void honks(){
        System.out.println("This car honks");
    }

// override toString() method that comes from Object Class
    // Implementing another body for the parent method


    @Override  // autogenerated
    public String toString() {  // click right +  generate + toString;
        return "Car{" +
                "make='" + make + '\'' +
                ", model='" + model + '\'' +
                ", color='" + color + '\'' +
                ", year=" + year +
                ", price=" + price +
                ", hasRoof=" + hasRoof +
                '}';
    }
}


